### ISSUE TITLE
InvalidArgumentException View [default.index] not found.

### ISSUE THREAD

**Issue by glockjt** [wardrobecms/wardrobe-archived#9]
I get there error for the index and when I want to preview posts.  Any idea how to fix this?  Thanks

**Comment by ericlbarnes** [comment]
Did you install it with `composer create-project wardrobe/wardrobe` or some other means?

**Comment by glockjt** [comment]
Yes I am and I just tried reinstalling and I got the same issue.

**Comment by ericlbarnes** [comment]
It has to just not be finding the theme files. Try running `php artisan wardrobe:themes` just in case that didn't run for you during install. 

If that doesn't fix it can you paste the whole backtrace?

**Comment by vanchelo** [comment]
Same error

``` php
[2013-11-07 06:50:08] log.ERROR: exception 'InvalidArgumentException' with message 'View [default.about] not found.' in /home/blog/www/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:135
Stack trace:
#0 /home/blog/www/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(76): Illuminate\View\FileViewFinder->findInPaths('default.about', Array)
#1 /home/blog/www/vendor/laravel/framework/src/Illuminate/View/Environment.php(115): Illuminate\View\FileViewFinder->find('default.about')
#2 /home/blog/www/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(206): Illuminate\View\Environment->make('default.about')
#3 /home/blog/www/public/themes/default/routes.php(16): Illuminate\Support\Facades\Facade::__callStatic('make', Array)
#4 /home/blog/www/public/themes/default/routes.php(16): Illuminate\Support\Facades\View::make('default.about')
#5 [internal function]: Wardrobe\Core\WardrobeServiceProvider->{closure}()
#6 /home/blog/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array)
#7 /home/blog/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable()
#8 /home/blog/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 /home/blog/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(574): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 /home/blog/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(550): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 /home/blog/www/public/index.php(49): Illuminate\Foundation\Application->run()
#12 {main} [] []
```

**Comment by vanchelo** [comment]
Because only running in https://github.com/wardrobecms/core/blob/develop/src/Wardrobe/Core/Controllers/BaseController.php#L27

``` php
Wardrobe::setupViews()
```

**Comment by Bushra230** [comment]
I get  error for the index and when I want to preview posts. Any idea how to fix this?
23. InvalidArgumentException
…\vendor\laravel\framework\src\Illuminate\View\FileViewFinder.php139
